; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "VirtualStore"
#define MyAppVersion "1.0.0.1"
#define MyAppPublisher "SistemasIg"
#define MyAppURL "https://www.VirtualStore.com.ar/"
#define MyAppExeName "VirtualStore.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8B6DEC6B-E338-4A3B-AC46-BFAD39B0B6D4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=VirtualStore
OutputBaseFilename=VirtualStore.Setup
SetupIconFile=C:\Users\usuario\Downloads\iconoroot.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\usuario\Desktop\VirtualStore\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\usuario\Desktop\VirtualStore\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup: Boolean;
var
  MySQLInstalled: Boolean;
  ResultCode: Integer; 
  
begin
  {if(ActiveLanguage = 'English')}
  if RegKeyExists(HKLM, 'SOFTWARE\MySQL AB') or RegKeyExists(HKCU, 'SOFTWARE\MySQL AB') then
    MySQLInstalled := True
  else
    MySQLInstalled := False;

  
  if not MySQLInstalled then
    begin

           if ActiveLanguage = 'english' then
               begin
                  MsgBox('MySQL is not installed on your system. Please download and install MySQL before using the application.' + #13#13 +
                     'You can download MySQL from the following link: https://dev.mysql.com/downloads/installer/', mbInformation, MB_OK);
               end;

           if ActiveLanguage = 'spanish' then
               begin
               MsgBox('MySQL no está instalado en su sistema. Por favor, descargue e instale MySQL antes de utilizar la aplicación.' + #13#13 +
                     'Puede descargar MySQL desde el siguiente enlace: https://dev.mysql.com/downloads/installer/', mbInformation, MB_OK);
               end;
      
            ShellExec('open', 'https://dev.mysql.com/downloads/installer/', '', '', SW_SHOWNORMAL, ewNoWait, ResultCode);
            Result := False; { Detener la instalación }



    end
  else
    Result := True; { Continuar con la instalación }
end;


